# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/linux-64/_libgcc_mutex-0.1-main.conda
https://repo.anaconda.com/pkgs/main/linux-64/blas-1.0-mkl.conda
https://repo.anaconda.com/pkgs/main/linux-64/ca-certificates-2020.7.22-0.conda
https://repo.anaconda.com/pkgs/main/linux-64/intel-openmp-2020.2-254.conda
https://repo.anaconda.com/pkgs/main/linux-64/ld_impl_linux-64-2.33.1-h53a641e_7.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgfortran-ng-7.3.0-hdf63c60_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libstdcxx-ng-9.1.0-hdf63c60_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pandoc-2.10.1-0.conda
https://conda.anaconda.org/conda-forge/linux-64/poppler-data-0.4.9-0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libgcc-ng-9.1.0-hdf63c60_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-2020.2-256.conda
https://conda.anaconda.org/conda-forge/linux-64/bzip2-1.0.8-h516909a_3.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/c-ares-1.16.1-h516909a_3.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/expat-2.2.9-he6710b0_2.conda
https://conda.anaconda.org/conda-forge/linux-64/freexl-1.0.5-h516909a_1002.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/geos-3.8.1-he6710b0_0.conda
https://conda.anaconda.org/conda-forge/linux-64/giflib-5.2.1-h516909a_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/icu-64.2-he1b5a44_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/jpeg-9d-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/json-c-0.13.1-hbfbb72e_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libblas-3.8.0-16_mkl.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libev-4.33-h516909a_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libffi-3.3-he6710b0_2.conda
https://conda.anaconda.org/conda-forge/linux-64/libiconv-1.16-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libsodium-1.0.18-h516909a_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libspatialindex-1.9.3-he1b5a44_3.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libuuid-2.32.1-h14c3975_1000.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libwebp-base-1.1.0-h516909a_3.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libxcb-1.14-h7b6447c_0.conda
https://conda.anaconda.org/conda-forge/linux-64/lz4-c-1.9.2-he1b5a44_3.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/ncurses-6.2-he6710b0_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/openssl-1.1.1h-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pcre-8.44-he6710b0_0.conda
https://conda.anaconda.org/conda-forge/linux-64/pixman-0.38.0-h516909a_1003.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/tbb-2020.3-hfd86e86_0.conda
https://conda.anaconda.org/conda-forge/linux-64/tzcode-2020a-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-kbproto-1.0.7-h14c3975_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libice-1.0.10-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-renderproto-0.11.1-h14c3975_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-xextproto-7.3.0-h14c3975_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-xproto-7.0.31-h14c3975_1007.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/xz-5.2.5-h7b6447c_0.conda
https://conda.anaconda.org/conda-forge/linux-64/yaml-0.2.5-h516909a_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/zlib-1.2.11-h7b6447c_3.conda
https://conda.anaconda.org/conda-forge/linux-64/boost-cpp-1.72.0-h8e57a91_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/glib-2.65.0-h3eb4bd4_0.conda
https://conda.anaconda.org/conda-forge/linux-64/hdf4-4.2.13-hf30be14_1003.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/hdf5-1.10.6-nompi_h3c11f04_101.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libcblas-3.8.0-16_mkl.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libedit-3.1.20191231-h14c3975_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libllvm10-10.0.1-hbcb73fb_5.conda
https://conda.anaconda.org/conda-forge/linux-64/libnghttp2-1.41.0-h8cfc5f6_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libpng-1.6.37-hed695b0_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libssh2-1.9.0-hab1572f_5.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libxml2-2.9.10-hee79883_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/readline-8.0-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tk-8.6.10-hbc83047_0.conda
https://conda.anaconda.org/conda-forge/linux-64/xerces-c-3.2.3-h8412b87_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libsm-1.2.3-h84519dc_1000.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libx11-1.6.12-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/zeromq-4.3.3-he1b5a44_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/zstd-1.4.5-h6597ccf_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/freetype-2.10.2-he06d7ca_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/kealib-1.4.13-h33137a7_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/krb5-1.17.1-hfafb76e_3.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libkml-1.3.0-hd79254b_1012.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libtiff-4.1.0-hc7e4089_6.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/sqlite-3.33.0-h62c20be_0.conda
https://conda.anaconda.org/conda-forge/linux-64/xorg-libxext-1.3.4-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libxrender-0.9.10-h516909a_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/fontconfig-2.13.1-h86ecdb6_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/lcms2-2.11-hbd6801e_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libcurl-7.71.1-hcdd3856_8.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libpq-12.3-h5513abc_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/openjpeg-2.3.1-h981e76c_3.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/python-3.8.5-h7579374_1.conda
https://conda.anaconda.org/conda-forge/noarch/async_generator-1.10-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/attrs-20.2.0-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/backcall-0.2.0-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/backports-1.0-py_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/cairo-1.16.0-hcf35c78_1003.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/certifi-2020.6.20-py38_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cfitsio-3.470-hf0d0db6_6.conda
https://conda.anaconda.org/conda-forge/noarch/click-7.1.2-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/cloudpickle-1.6.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/curl-7.71.1-he644dc0_8.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/decorator-4.4.2-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/defusedxml-0.6.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/fsspec-0.8.3-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/future-0.18.2-py38_1.conda
https://conda.anaconda.org/conda-forge/noarch/heapdict-1.0.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/idna-2.10-pyh9f0ad1d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/ipython_genutils-0.2.0-py38_0.conda
https://repo.anaconda.com/pkgs/main/noarch/itsdangerous-1.1.0-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/kiwisolver-1.2.0-py38hfd86e86_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/llvmlite-0.34.0-py38h269e1b5_4.conda
https://repo.anaconda.com/pkgs/main/linux-64/locket-0.2.0-py38_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/msgpack-python-1.0.0-py38hfd86e86_1.conda
https://conda.anaconda.org/conda-forge/noarch/nest-asyncio-1.4.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/olefile-0.46-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pandocfilters-1.4.2-py38_1.conda
https://conda.anaconda.org/conda-forge/noarch/param-1.9.3-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/parso-0.7.1-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/postgresql-12.3-h8573dbc_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/proj-7.1.0-h966b41f_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/prometheus_client-0.8.0-pyh9f0ad1d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/psutil-5.7.2-py38h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ptyprocess-0.6.0-py38_0.conda
https://conda.anaconda.org/conda-forge/noarch/pycparser-2.20-pyh9f0ad1d_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyparsing-2.4.7-pyh9f0ad1d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pyrsistent-0.17.3-py38h7b6447c_0.conda
https://conda.anaconda.org/conda-forge/noarch/pyshp-2.1.2-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/python_abi-3.8-1_cp38.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/pytz-2020.1-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyyaml-5.3.1-py38h7b6447c_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyzmq-19.0.2-py38he6710b0_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/rtree-0.9.4-py38_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/send2trash-1.5.0-py38_0.conda
https://repo.anaconda.com/pkgs/main/noarch/six-1.15.0-py_0.conda
https://conda.anaconda.org/conda-forge/noarch/sortedcontainers-2.2.2-pyh9f0ad1d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/tblib-1.7.0-py_0.conda
https://conda.anaconda.org/conda-forge/noarch/testpath-0.4.4-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/threadpoolctl-2.1.0-pyh5ca1d4c_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/toolz-0.11.1-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tornado-6.0.4-py38h7b6447c_1.conda
https://conda.anaconda.org/conda-forge/noarch/tqdm-4.50.0-pyh9f0ad1d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/typing_extensions-3.7.4.3-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/webencodings-0.5.1-py38_1.conda
https://repo.anaconda.com/pkgs/main/noarch/werkzeug-1.0.1-py_0.conda
https://conda.anaconda.org/conda-forge/noarch/zipp-3.2.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/cffi-1.14.3-py38he30daa8_0.conda
https://conda.anaconda.org/conda-forge/linux-64/chardet-3.0.4-py38h32f6830_1007.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/click-plugins-1.1.1-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/cligj-0.5.0-py38_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cycler-0.10.0-py38_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cytoolz-0.11.0-py38h7b6447c_0.conda
https://conda.anaconda.org/conda-forge/noarch/dask-core-2.29.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/entrypoints-0.3-py38h32f6830_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/geotiff-1.6.0-ha04d9d0_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/importlib-metadata-2.0.0-py38h32f6830_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/jedi-0.17.2-py38_0.conda
https://conda.anaconda.org/conda-forge/linux-64/libdap4-3.20.6-h1d1bd15_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libnetcdf-4.7.4-nompi_h84807e1_105.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libspatialite-4.3.0a-h57f1b35_1039.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/markupsafe-1.1.1-py38h1e0a361_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/mistune-0.8.4-py38h1e0a361_1001.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/mkl-service-2.3.0-py38he904b0f_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/multipledispatch-0.6.0-py38_0.conda
https://conda.anaconda.org/conda-forge/noarch/packaging-20.4-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/partd-1.1.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pexpect-4.8.0-py38h32f6830_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pickleshare-0.7.5-py38h32f6830_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pillow-7.2.0-py38h9776b28_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/poppler-0.89.0-h4190859_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pyproj-2.6.1.post1-py38h8e47818_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pysocks-1.7.1-py38h32f6830_1.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/python-dateutil-2.8.1-py_0.conda
https://conda.anaconda.org/conda-forge/noarch/pyviz_comms-0.7.6-pyh9f0ad1d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/setuptools-49.6.0-py38_1.conda
https://conda.anaconda.org/conda-forge/linux-64/terminado-0.9.1-py38h32f6830_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/tiledb-2.0.8-h3effe38_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/traitlets-5.0.4-py38_0.conda
https://conda.anaconda.org/conda-forge/noarch/zict-2.0.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/argon2-cffi-20.1.0-py38h7b6447c_1.conda
https://conda.anaconda.org/conda-forge/noarch/backports.functools_lru_cache-1.6.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/bleach-3.2.1-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/brotlipy-0.7.0-py38h516909a_1000.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/cryptography-3.1.1-py38h766eaa4_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/distributed-2.29.0-py38h32f6830_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/gunicorn-20.0.4-py38_0.conda
https://conda.anaconda.org/conda-forge/noarch/importlib_metadata-2.0.0-0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jinja2-2.11.2-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/joblib-0.17.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/jupyter_core-4.6.3-py38h32f6830_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libgdal-3.1.2-hf6fc319_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/markdown-3.2.2-py38_0.conda
https://conda.anaconda.org/conda-forge/noarch/munch-2.5.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/numpy-base-1.19.1-py38hfa32c7d_0.conda
https://conda.anaconda.org/conda-forge/noarch/pygments-2.7.1-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/flask-1.1.2-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/jsonschema-3.2.0-py38_1.conda
https://conda.anaconda.org/conda-forge/noarch/jupyter_client-6.1.7-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jupyterlab_pygments-0.1.2-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pyopenssl-19.1.0-py38_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/wcwidth-0.2.5-pyh9f0ad1d_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/nbformat-5.0.7-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/prompt-toolkit-3.0.7-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/urllib3-1.25.10-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/ipython-7.18.1-py38h5ca1d4c_0.conda
https://conda.anaconda.org/conda-forge/noarch/nbclient-0.5.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/requests-2.24.0-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ipykernel-5.3.4-py38h23f93f0_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/nbconvert-6.0.7-py38h32f6830_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/owslib-0.20.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pyct-0.4.8-py38_0.conda
https://conda.anaconda.org/conda-forge/noarch/pyepsg-0.4.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/colorcet-2.0.2-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/notebook-6.1.4-py38_0.conda
https://conda.anaconda.org/conda-forge/linux-64/gdal-3.1.2-py38hb61cb63_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/matplotlib-base-3.3.2-py38h91b0d89_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/shapely-1.7.1-py38hc7361b7_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/fiona-1.8.17-py38h676c6b2_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/geopandas-0.8.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/panel-0.9.7-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/bokeh-2.2.1-py38_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cftime-1.2.1-py38heb32a55_0.conda
https://conda.anaconda.org/conda-forge/linux-64/netcdf4-1.5.4-nompi_py38hec8b9af_102.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/datashape-0.5.4-py38_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_fft-1.2.0-py38h23d657b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_random-1.1.1-py38h0573a6f_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-1.19.1-py38hbc911f0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numba-0.51.2-py38h0573a6f_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/pandas-1.1.2-py38he6710b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/scipy-1.5.2-py38h0b6359f_0.conda
https://conda.anaconda.org/conda-forge/noarch/autograd-1.3-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/cartopy-0.18.0-py38h4f3c6b6_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/catboost-0.24-py38h32f6830_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/dask-2.29.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/holoviews-1.13.4-pyh9f0ad1d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/patsy-0.5.1-py38_0.conda
https://conda.anaconda.org/conda-forge/linux-64/scikit-learn-0.23.2-py38hee58b96_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/xarray-0.16.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/autograd-gamma-0.4.3-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/datashader-0.11.1-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/geoviews-core-1.8.2-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/statsmodels-0.11.1-py38h7b6447c_0.conda
https://conda.anaconda.org/conda-forge/noarch/category_encoders-2.2.2-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/geoviews-1.8.2-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/lifelines-0.25.4-py_0.tar.bz2
