# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://conda.anaconda.org/conda-forge/linux-64/_libgcc_mutex-0.1-conda_forge.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/blas-1.0-mkl.conda
https://repo.anaconda.com/pkgs/main/linux-64/ca-certificates-2020.7.22-0.conda
https://repo.anaconda.com/pkgs/main/linux-64/intel-openmp-2020.2-254.conda
https://conda.anaconda.org/conda-forge/linux-64/ld_impl_linux-64-2.35-h769bd43_9.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libgfortran-ng-7.3.0-hdf63c60_0.conda
https://conda.anaconda.org/conda-forge/linux-64/libstdcxx-ng-9.3.0-h2ae2ef3_17.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pandoc-2.10.1-0.conda
https://conda.anaconda.org/conda-forge/linux-64/libgomp-9.3.0-h5dbcf3e_17.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/mkl-2020.2-256.conda
https://conda.anaconda.org/conda-forge/linux-64/_openmp_mutex-4.5-1_gnu.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libgcc-ng-9.3.0-h5dbcf3e_17.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/blosc-1.20.1-he1b5a44_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/brotli-1.0.9-he6710b0_0.conda
https://conda.anaconda.org/conda-forge/linux-64/bzip2-1.0.8-h516909a_3.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/charls-2.1.0-he6710b0_2.conda
https://conda.anaconda.org/conda-forge/linux-64/firefox-81.0-he1b5a44_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/geckodriver-0.27.0-he1b5a44_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/giflib-5.1.9-h516909a_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/jpeg-9b-h024ee3a_2.conda
https://conda.anaconda.org/conda-forge/linux-64/jxrlib-1.1-h516909a_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libaec-1.0.4-he6710b0_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libffi-3.2.1-hf484d3e_1007.conda
https://conda.anaconda.org/conda-forge/linux-64/libsodium-1.0.18-h516909a_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libzopfli-1.0.3-he6710b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/lz4-c-1.9.2-he6710b0_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/ncurses-6.2-he6710b0_1.conda
https://conda.anaconda.org/conda-forge/linux-64/openssl-1.1.1h-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/snappy-1.1.8-he1b5a44_3.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/tbb-2020.3-hfd86e86_0.conda
https://conda.anaconda.org/conda-forge/linux-64/xz-5.2.5-h516909a_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/yaml-0.2.5-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/zlib-1.2.11-h516909a_1009.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libedit-3.1.20191231-he28a2e2_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libllvm10-10.0.1-hbcb73fb_5.conda
https://repo.anaconda.com/pkgs/main/linux-64/libpng-1.6.37-hbc83047_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libprotobuf-3.13.0-hd408876_0.conda
https://conda.anaconda.org/conda-forge/linux-64/readline-8.0-he28a2e2_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/tk-8.6.10-hed695b0_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/zeromq-4.3.3-he1b5a44_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/zstd-1.4.5-h9ceee32_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/freetype-2.10.2-h5ab3b9f_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libtiff-4.1.0-h2733197_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/sqlite-3.33.0-h62c20be_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/lcms2-2.11-h396b838_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libwebp-1.0.1-h8e7db2f_0.conda
https://conda.anaconda.org/conda-forge/linux-64/openjpeg-2.3.1-h981e76c_3.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/python-3.8.5-h1103e12_9_cpython.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/appdirs-1.4.4-py_0.conda
https://conda.anaconda.org/conda-forge/noarch/asn1crypto-1.4.0-pyh9f0ad1d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/attrs-20.2.0-py_0.conda
https://repo.anaconda.com/pkgs/main/noarch/backcall-0.2.0-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/blinker-1.4-py38_0.conda
https://conda.anaconda.org/conda-forge/noarch/cachetools-4.1.1-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/certifi-2020.6.20-py38_0.conda
https://conda.anaconda.org/conda-forge/noarch/click-7.1.2-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/cloudpickle-1.6.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/configparser-5.0.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/decorator-4.4.2-py_0.conda
https://repo.anaconda.com/pkgs/main/noarch/defusedxml-0.6.0-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/distlib-0.3.1-py38_0.conda
https://conda.anaconda.org/conda-forge/noarch/filelock-3.0.12-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/fsspec-0.6.3-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/future-0.18.2-py38_1.conda
https://conda.anaconda.org/conda-forge/noarch/gorilla-0.3.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/idna-2.10-pyh9f0ad1d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/ipython_genutils-0.2.0-py38_0.conda
https://conda.anaconda.org/conda-forge/noarch/itsdangerous-1.1.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jmespath-0.10.0-pyh9f0ad1d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/json5-0.9.5-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/kiwisolver-1.2.0-py38hfd86e86_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/llvmlite-0.34.0-py38h269e1b5_4.conda
https://repo.anaconda.com/pkgs/main/linux-64/mccabe-0.6.1-py38_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/mistune-0.8.4-py38h7b6447c_1000.conda
https://repo.anaconda.com/pkgs/main/linux-64/mypy_extensions-0.4.3-py38_0.conda
https://repo.anaconda.com/pkgs/main/noarch/olefile-0.46-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pandocfilters-1.4.2-py38_1.conda
https://repo.anaconda.com/pkgs/main/noarch/param-1.9.3-py_0.conda
https://repo.anaconda.com/pkgs/main/noarch/parso-0.7.0-py_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pathspec-0.7.0-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pickleshare-0.7.5-py38_1000.conda
https://conda.anaconda.org/conda-forge/noarch/poyo-0.5.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/prometheus_client-0.8.0-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ptyprocess-0.6.0-py38_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pycodestyle-2.6.0-py_0.conda
https://conda.anaconda.org/conda-forge/noarch/pycparser-2.20-pyh9f0ad1d_2.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/pyflakes-2.2.0-py_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pyparsing-2.4.7-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyrsistent-0.17.3-py38h7b6447c_0.conda
https://conda.anaconda.org/conda-forge/noarch/python-editor-1.0.4-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/python-json-logger-0.1.11-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/python_abi-3.8-1_cp38.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/pytz-2020.1-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyyaml-5.3.1-py38h7b6447c_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyzmq-19.0.2-py38he6710b0_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/regex-2020.7.14-py38h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/send2trash-1.5.0-py38_0.conda
https://conda.anaconda.org/conda-forge/noarch/six-1.15.0-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/slicer-0.0.3-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/smmap-3.0.4-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/sqlalchemy-1.3.13-py38h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/sqlparse-0.3.1-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/tabulate-0.8.7-py38_0.conda
https://repo.anaconda.com/pkgs/main/noarch/testpath-0.4.4-py_0.conda
https://repo.anaconda.com/pkgs/main/noarch/threadpoolctl-2.1.0-pyh5ca1d4c_0.conda
https://repo.anaconda.com/pkgs/main/noarch/toml-0.10.1-py_0.conda
https://conda.anaconda.org/conda-forge/noarch/toolz-0.11.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/toposort-1.5-py_3.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/tornado-6.0.4-py38h7b6447c_1.conda
https://repo.anaconda.com/pkgs/main/noarch/tqdm-4.49.0-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/typed-ast-1.4.1-py38h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/noarch/typing_extensions-3.7.4.3-py_0.conda
https://repo.anaconda.com/pkgs/main/noarch/wcwidth-0.2.5-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/webencodings-0.5.1-py38_1.conda
https://conda.anaconda.org/conda-forge/noarch/werkzeug-1.0.1-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/wheel-0.35.1-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/whichcraft-0.6.1-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/zipp-3.1.0-py_0.conda
https://repo.anaconda.com/pkgs/main/noarch/black-19.10b0-py_0.conda
https://conda.anaconda.org/conda-forge/linux-64/cffi-1.14.3-py38h5bae8af_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/cfgv-3.2.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/chardet-3.0.4-py38h32f6830_1007.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/cycler-0.10.0-py38_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cytoolz-0.11.0-py38h7b6447c_0.conda
https://conda.anaconda.org/conda-forge/noarch/dask-core-2.29.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/docker-pycreds-0.4.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/editdistance-0.5.3-py38h950e882_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/entrypoints-0.3-py38h32f6830_1001.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/gitdb-4.0.5-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/importlib-metadata-1.7.0-py38_0.conda
https://conda.anaconda.org/conda-forge/noarch/isodate-0.6.0-py_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/jedi-0.17.2-py38_0.conda
https://conda.anaconda.org/conda-forge/noarch/markdown-it-py-0.5.5-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/markupsafe-1.1.1-py38h1e0a361_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/mkl-service-2.3.0-py38he904b0f_0.conda
https://repo.anaconda.com/pkgs/main/noarch/packaging-20.4-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pexpect-4.8.0-py38_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pillow-7.2.0-py38hb39fc2d_0.conda
https://conda.anaconda.org/conda-forge/linux-64/pluggy-0.13.1-py38h32f6830_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyaml-20.4.0-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pysocks-1.7.1-py38h32f6830_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/python-dateutil-2.8.1-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/pyviz_comms-0.7.6-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/setuptools-46.4.0-py38_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/terminado-0.8.3-py38_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/traitlets-5.0.4-py38_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/virtualenv-20.0.20-py38_1.conda
https://conda.anaconda.org/conda-forge/linux-64/websocket-client-0.57.0-py38h32f6830_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/anyconfig-0.9.10-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/argon2-cffi-20.1.0-py38h7b6447c_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/arrow-0.16.0-py38_0.conda
https://conda.anaconda.org/conda-forge/noarch/binaryornot-0.4.4-py_1.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/bleach-3.2.1-py_0.conda
https://conda.anaconda.org/conda-forge/linux-64/brotlipy-0.7.0-py38h516909a_1000.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/cryptography-3.1.1-py38h766eaa4_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/flake8-3.8.3-py_0.conda
https://repo.anaconda.com/pkgs/main/noarch/gitpython-3.1.9-py_1.conda
https://conda.anaconda.org/conda-forge/linux-64/gunicorn-20.0.4-py38h32f6830_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/identify-1.5.5-pyh9f0ad1d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/importlib_metadata-1.7.0-0.conda
https://conda.anaconda.org/conda-forge/noarch/jinja2-2.11.2-pyh9f0ad1d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/joblib-0.16.0-py_0.conda
https://conda.anaconda.org/conda-forge/linux-64/jupyter_core-4.6.3-py38h32f6830_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/mako-1.1.3-pyh9f0ad1d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/markdown-3.2.2-py38_0.conda
https://conda.anaconda.org/conda-forge/noarch/networkx-2.5-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/nodeenv-1.5.0-pyh9f0ad1d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/numpy-base-1.19.1-py38hfa32c7d_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pip-20.2.3-py38_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/protobuf-3.13.0-py38he6710b0_1.conda
https://repo.anaconda.com/pkgs/main/noarch/pygments-2.7.1-py_0.conda
https://conda.anaconda.org/conda-forge/noarch/alembic-1.4.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/flask-1.1.2-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jinja2-time-0.2.0-py_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/jsonschema-3.2.0-py38_1.conda
https://conda.anaconda.org/conda-forge/linux-64/jupyter_client-5.3.4-py38_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pip-tools-5.3.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pre-commit-2.7.1-py38h32f6830_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/prompt-toolkit-3.0.7-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyjwt-1.7.1-py38_0.conda
https://conda.anaconda.org/conda-forge/linux-64/pyopenssl-19.1.0-py38_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/ipython-7.18.1-py38h5ca1d4c_0.conda
https://repo.anaconda.com/pkgs/main/noarch/nbformat-5.0.7-py_0.conda
https://repo.anaconda.com/pkgs/main/noarch/oauthlib-3.1.0-py_0.conda
https://conda.anaconda.org/conda-forge/noarch/pre_commit-2.7.1-0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/prometheus_flask_exporter-0.18.0-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/urllib3-1.25.10-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/ipykernel-5.3.4-py38h5ca1d4c_0.conda
https://conda.anaconda.org/conda-forge/noarch/jupytext-1.6.0-pyh9f0ad1d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/nbconvert-5.6.1-py38_0.conda
https://conda.anaconda.org/conda-forge/noarch/requests-2.24.0-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/selenium-3.141.0-py38h1e0a361_1001.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/azure-core-1.8.1-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/cookiecutter-1.6.0-py38_1000.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/databricks-cli-0.9.1-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/docker-py-4.3.1-py38_4.conda
https://repo.anaconda.com/pkgs/main/linux-64/notebook-6.1.4-py38_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyct-0.4.8-py38_0.conda
https://conda.anaconda.org/conda-forge/noarch/querystring_parser-1.2.4-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/requests-oauthlib-1.3.0-pyh9f0ad1d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/colorcet-2.0.2-py_0.conda
https://repo.anaconda.com/pkgs/main/noarch/jupyterlab_server-1.2.0-py_0.conda
https://conda.anaconda.org/conda-forge/noarch/kedro-0.16.5-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/msrest-0.6.19-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/azure-storage-blob-12.5.0-pyh9f0ad1d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/jupyterlab-2.2.6-py_0.conda
https://conda.anaconda.org/conda-forge/linux-64/pywavelets-1.1.1-py38hab2c0dc_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/imageio-2.9.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/bokeh-2.2.1-py38_0.conda
https://repo.anaconda.com/pkgs/main/noarch/panel-0.9.7-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/imagecodecs-2020.5.30-py38h567f118_1.conda
https://conda.anaconda.org/conda-forge/noarch/tifffile-2020.10.1-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/matplotlib-base-3.3.1-py38h817c723_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_fft-1.2.0-py38h23d657b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_random-1.1.1-py38h0573a6f_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-1.19.1-py38hbc911f0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numba-0.51.2-py38h0573a6f_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/pandas-1.1.2-py38he6710b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/scipy-1.5.2-py38h0b6359f_0.conda
https://conda.anaconda.org/conda-forge/noarch/autograd-1.3-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/holoviews-1.13.4-py_0.conda
https://conda.anaconda.org/conda-forge/linux-64/mlflow-1.11.0-py38h32f6830_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/patsy-0.5.1-py38_0.conda
https://conda.anaconda.org/conda-forge/linux-64/scikit-image-0.17.2-py38hc5bc63f_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/scikit-learn-0.23.2-py38h0573a6f_0.conda
https://conda.anaconda.org/powerai/noarch/aif360-0.2.2-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/autograd-gamma-0.4.3-pyh9f0ad1d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/hvplot-0.6.0-py_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/lightgbm-2.3.0-py38he6710b0_0.conda
https://conda.anaconda.org/conda-forge/noarch/scikit-optimize-0.8.1-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/shap-0.36.0-py38hc5bc63f_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/lifelines-0.25.4-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/ngboost-0.3.6-py_0.tar.bz2
